"""add card fields to reports

Revision ID: 2baf3ab3eebe
Revises: 53dce266bc0c
Create Date: 2025-10-21 14:32:34.237133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2baf3ab3eebe'
down_revision: Union[str, Sequence[str], None] = '53dce266bc0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('title_description', sa.String(length=300), nullable=True))
    op.add_column('reports', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('reports', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('reports', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'image_url')
    op.drop_column('reports', 'thumbnail_url')
    op.drop_column('reports', 'description')
    op.drop_column('reports', 'title_description')
    # ### end Alembic commands ###
