"""add parent_id to groups

Revision ID: 53dce266bc0c
Revises: 0f283f292242
Create Date: 2025-10-20 09:04:17.650925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dce266bc0c'
down_revision: Union[str, Sequence[str], None] = '0f283f292242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('parent_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_groups_parent_id'), 'groups', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'groups', 'groups', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reports_group_id'), table_name='reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reports_group_id'), 'reports', ['group_id'], unique=False)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_groups_parent_id'), table_name='groups')
    op.drop_column('groups', 'parent_id')
    # ### end Alembic commands ###
