"""create reports table

Revision ID: a0803ff7c469
Revises: f7e764b5b078
Create Date: 2025-10-14 16:17:42.206831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0803ff7c469'
down_revision: Union[str, Sequence[str], None] = 'f7e764b5b078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'report_id')
    op.drop_column('groups', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('workspace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('report_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
